#ifndef TXT_STRG_H
#define TXT_STRG_H

/*
*/


#define TXT_F_CREATE            "Skladiste kreirano!"
#define TXT_PERR_F_CREATE	"\nKreiranje datoteke (skladista) nije moguce"

#define TXT_PUT_ART             "Unos artikla uspio."
#define TXT_SUBSTITUTE_ART      "Promjena artikla uspjela. "
#define TXT_ERR_PUT_ART		"Unos artika nije uspio - "
#define TXT_2ADDED		"Artikl pridodan vec postojecem."
#define TXT_ERR_ART_NO_MEM	"Nema vise memorije za artikle! Ucitana nepotpuna baza."
#define TXT_ERR_NO_MEM          TXT_ERR_PUT_ART "nema dovoljno memorije!"
#define TXT_ERR_2ADDED		TXT_ERR_PUT_ART "dodavanje vec postojeceg artikla premasuje dozvoljenu kolicinu artikla!"
#define TXT_ERR_AMOUNT          TXT_ERR_PUT_ART "dosegnuta maksimalna kolicina artikla!"

#define TXT_ERR_NO_ARTICLE      "Izdavanje artikla nije uspjelo - trazeni artikl ne postoji!"
#define TXT_ERR_NEGATIVE_AMOUNT "Izdavanje artikla nije uspjelo -  zatrazena kolicina veca od postojece!"

#define TXT_ERR_F_SAVE		"Pohrana promjene baze podataka nije moguca!"
#define TXT_F_SAVE		"Pohrana promjene baze podataka uspjesno obavljena."
#define TXT_ERR_BKP             "Sigurnosna kopija podataka nije pohranjena!"


/*
*/

#endif
