#ifndef TXT_STRG_H
#define TXT_STRG_H

/*
*/


#define TXT_F_CREATE            "\nSkladiste kreirano!"
#define TXT_PERR_F_CREATE	"\nKreiranje datoteke (skladista) nije moguce"

#define TXT_ERR_PUT_ART		"\nUnos artika nije uspio - "
#define TXT_2ADDED		"\nArtikl pridodan vec postojecem!"
#define TXT_ERR_ART_NO_MEM	"nema vise memorije za artikle!"
#define TXT_ERR_2ADDED		"dodavanje vec postojeceg artikla premasuje dozvoljenu kolicinu artikla!"

#define TXT_PERR_F_SAVE		"\nPohrana promjene baze podataka nije moguca"
#define TXT_F_SAVE		"\nPohrana promjene baze podataka uspjesno obavljena."


/*
*/

#endif
